import Head from 'next/head'
import Feed from '../components/feed/Feed'

import Sidebar from '../components/sidebar/Sidebar'
import Widgets from '../components/widgets/Widgets'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="bg-black min-h-screen flex  max-w-[1500px] mx-auto">


        <Sidebar />


        <Feed />

        <Widgets />

      </main>


    </div>
  )
}



